---
# set app specific ufw rules 
- name: Allow public access to tcp port 22
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

# broker port
- name: Allow public to tcp port 9092
  community.general.ufw:
    rule: allow
    port: '9092'
    proto: tcp

# controller port
- name: Allow private cluster access to tcp port 9093
  community.general.ufw:
    rule: allow
    port: '9093'
    proto: tcp
    from_ip: "{{ item.instance.ip_priv1 }}"
  loop: "{{ kafka_data.server }}"

# async to avoid connection disruption
- name: Enable ufw
  community.general.ufw:
    state: enabled
  async: 60
  poll: 0