---
# configure kafka
- name: configure kafka servers
  hosts: kafka
  any_errors_fatal: true
  user: root
  vars_files:
    - group_vars/kafka/vars
    - group_vars/kafka/secret_vars
  roles:
    - common
    - kafka
    - post