# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files to install dependencies
COPY package.json package-lock.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy rest of the source code
COPY . .

# Build the project (TypeScript compilation)
RUN npm run build

# Expose port if needed (MCP communicates over stdio typically, so not necessary to expose ports)

# Start the MCP server
CMD ["node", "dist/index.js"]
